package pack

import (
	"fmt"
	"strings"

	"rotor/internal/luau/cst"
)

// runtimePrelude is the fixed runtime the generated bundle starts with: a virtual
// instance type (Name/ClassName/Parent, child-by-name indexing, FindFirstChild /
// WaitForChild / GetChildren / GetFullName) and a require polyfill that runs each
// ModuleScript closure once (memoized), with a Roblox-faithful recursive-require
// error, falling back to the real require for anything outside the bundle.
//
// A reconstructed DataModel root additionally stands in for `game` (see EmitLuau): its
// metatable serves reconstructed services from `GetService`/`FindService` and delegates
// anything else to the host game, and child lookups that miss the reconstructed tree
// fall through to the matching real instance (`realOf`). So absolute instance paths like
// `game:GetService("X"):WaitForChild("Y")` resolve inside the bundle while real
// services/instances keep working. `realGame` is the host DataModel, or nil for a
// standalone model / a host without `game`, which disables the fallback entirely.
const runtimePrelude = `-- Generated by rotor pack. Self-contained: rebuilds the project's instance tree
-- and resolves requires against it. Runs anywhere Luau runs (no Rojo at runtime).
local realRequire = require
local realGame = game
local Instances = {}
local methods
local function virtualChild(self, name)
	for _, c in ipairs(self._children) do
		if c.Name == name then
			return c
		end
	end
	return nil
end
local function realOf(self)
	local r = rawget(self, "_real")
	if r ~= nil then
		return r or nil
	end
	local found
	if self.Parent == nil then
		found = realGame
	else
		local pr = realOf(self.Parent)
		found = pr ~= nil and pr:FindFirstChild(self.Name) or nil
	end
	rawset(self, "_real", found or false)
	return found
end
local function findFirstChild(self, name)
	local c = virtualChild(self, name)
	if c ~= nil then
		return c
	end
	local r = realOf(self)
	return r ~= nil and r:FindFirstChild(name) or nil
end
local function waitForChild(self, name, timeout)
	local c = virtualChild(self, name)
	if c ~= nil then
		return c
	end
	local r = realOf(self)
	if r ~= nil then
		return r:WaitForChild(name, timeout)
	end
	return nil
end
local function getChildren(self)
	local t = {}
	for i = 1, #self._children do
		t[i] = self._children[i]
	end
	return t
end
local function getFullName(self)
	local parts, cur = {}, self
	while cur do
		table.insert(parts, 1, cur.Name)
		cur = cur.Parent
	end
	return table.concat(parts, ".")
end
local function getService(self, name)
	local c = virtualChild(self, name)
	if c ~= nil then
		return c
	end
	if realGame ~= nil then
		return realGame:GetService(name)
	end
	error("rotor pack: service '" .. tostring(name) .. "' is not in the bundle", 2)
end
methods = {
	FindFirstChild = findFirstChild,
	WaitForChild = waitForChild,
	GetChildren = getChildren,
	GetFullName = getFullName,
}
local dmMethods = {
	GetService = getService,
	FindService = getService,
}
local MT = {
	__index = function(self, key)
		local m = methods[key]
		if m ~= nil then
			return m
		end
		return findFirstChild(self, key)
	end,
	__tostring = function(self)
		return self.Name
	end,
}
local DataModelMT = {
	__index = function(self, key)
		local dm = dmMethods[key]
		if dm ~= nil then
			return dm
		end
		local m = methods[key]
		if m ~= nil then
			return m
		end
		local child = virtualChild(self, key)
		if child ~= nil then
			return child
		end
		if realGame ~= nil then
			local v = realGame[key]
			if type(v) == "function" then
				return function(_, ...)
					return v(realGame, ...)
				end
			end
			return v
		end
		return nil
	end,
	__tostring = function(self)
		return self.Name
	end,
}
local function mk(id, className, name)
	local mt = MT
	if className == "DataModel" then
		mt = DataModelMT
	end
	local self = setmetatable({ _id = id, _children = {}, ClassName = className, Name = name, Parent = nil }, mt)
	Instances[id] = self
	return self
end
local function setParent(child, parent)
	child.Parent = parent
	table.insert(parent._children, child)
end
local cache, loading = {}, {}
-- @self for a module: the package's source root — the child of the package
-- folder (the folder directly under a node_modules "@scope") on the path down
-- to the requiring module. Lets pesde-style packages (@rbxts/ripple) use @self/x.
-- Read .Parent without triggering __index (which, for a nil/root Parent, would
-- recurse into findFirstChild/realOf forever). Parent is a plain rawset field.
local function parentOf(inst)
	return rawget(inst, "Parent")
end
local function pkgSelf(from)
	local cur, childOfPkg = from, from
	local p = parentOf(cur)
	while p ~= nil and string.sub(p.Name, 1, 1) ~= "@" do
		childOfPkg = cur
		cur = p
		p = parentOf(cur)
	end
	return childOfPkg
end
-- Resolve a Luau require-by-string path (./x, ../x, nested a/b, @self/x) to a
-- virtual instance, relative to the requiring ModuleScript (from). Mirrors Luau
-- string-require directory rules: an init-style module (one with children) is
-- its own directory; a leaf module's directory is its parent.
local function resolvePath(from, path)
	local segs = {}
	for s in string.gmatch(path, "[^/]+") do
		segs[#segs + 1] = s
	end
	local base, i
	if segs[1] == "@self" then
		base, i = pkgSelf(from), 2
	else
		base = (#from._children > 0) and from or parentOf(from)
		i = 1
	end
	for j = i, #segs do
		local s = segs[j]
		if s == ".." then
			base = base and parentOf(base)
		elseif s ~= "." then
			base = base and virtualChild(base, s)
		end
		if base == nil then
			return nil
		end
	end
	return base
end
local loadModule, moduleRequire
loadModule = function(target)
	local id = target._id
	local c = cache[id]
	if c ~= nil then
		return c.value
	end
	if loading[id] then
		error("Requested module was required recursively", 2)
	end
	loading[id] = true
	local value = target._impl(target, function(p)
		return moduleRequire(target, p)
	end)
	loading[id] = nil
	cache[id] = { value = value }
	return value
end
-- The require seen by a module's closure. String paths resolve against the
-- reconstructed tree relative to the requiring script; instance requires run the
-- memoized closure; anything else (real instance/service paths, missing modules)
-- falls back to the host require.
moduleRequire = function(from, target)
	if type(target) == "string" then
		local inst = from ~= nil and resolvePath(from, target) or nil
		if inst ~= nil and inst.ClassName == "ModuleScript" then
			return loadModule(inst)
		end
		return realRequire(target)
	end
	if type(target) == "table" and rawget(target, "_id") ~= nil and target.ClassName == "ModuleScript" then
		return loadModule(target)
	end
	return realRequire(target)
end
local function rotorRequire(target)
	return moduleRequire(nil, target)
end
local function runScripts(inst)
	if inst.ClassName == "Script" or inst.ClassName == "LocalScript" then
		inst._impl(inst, function(p)
			return moduleRequire(inst, p)
		end)
	end
	for _, c in ipairs(inst._children) do
		runScripts(c)
	end
end
`

// EmitLuau renders a self-reconstructing Luau bundle for the given model trees. If
// entry is non-empty it is resolved (a dotted instance path, optionally including the
// root name); a ModuleScript entry returns `require(entry)`, a Script/LocalScript entry
// runs its body; otherwise the bundle runs every Script/LocalScript and returns the root
// instance. When the root is a DataModel the bundle binds `game` to the reconstructed
// root, so absolute `game:GetService(...)` paths resolve against the bundle (see
// runtimePrelude); otherwise the host game's fallback is disabled.
func EmitLuau(roots []*Instance, entry string) (string, error) {
	if len(roots) == 0 {
		return "", fmt.Errorf("model has no instances")
	}
	root := roots[0]

	var all []*Instance
	parentID := map[*Instance]int{}
	var assign func(n, parent *Instance)
	assign = func(n, parent *Instance) {
		n.id = len(all) + 1
		all = append(all, n)
		if parent != nil {
			parentID[n] = parent.id
		}
		for _, c := range n.Children {
			assign(c, n)
		}
	}
	assign(root, nil)

	var entryInst *Instance
	if entry != "" {
		entryInst = resolveEntry(root, entry)
		if entryInst == nil {
			return "", fmt.Errorf("entry %q not found in the model", entry)
		}
	}

	rootIsGame := root.ClassName == "DataModel"

	var b strings.Builder
	b.WriteString(runtimePrelude)
	if !rootIsGame {
		// Standalone model (no host DataModel it stands in for): disable the
		// real-instance fallback so child/service misses don't reach the host game.
		b.WriteString("realGame = nil\n")
	}
	b.WriteString("\n-- === instance tree ===\n")
	for _, n := range all {
		fmt.Fprintf(&b, "local i%d = mk(%d, %s, %s)\n", n.id, n.id, luauString(n.ClassName), luauString(n.Name))
		if pid := parentID[n]; pid != 0 {
			fmt.Fprintf(&b, "setParent(i%d, i%d)\n", n.id, pid)
		}
		if n.ClassName == "StringValue" {
			fmt.Fprintf(&b, "i%d.Value = %s\n", n.id, luauString(n.Value))
		}
	}
	if rootIsGame {
		// Bind `game` to the reconstructed root so the modules' absolute
		// game:GetService(...) paths resolve against the bundle.
		fmt.Fprintf(&b, "local game = i%d\n", root.id)
	}

	b.WriteString("\n-- === module/script implementations ===\n")
	for _, n := range all {
		if n.IsScript() {
			emitImpl(&b, n)
		}
	}

	b.WriteString("\n-- === entry ===\n")
	switch {
	case entryInst == nil:
		fmt.Fprintf(&b, "runScripts(i%d)\nreturn i%d\n", root.id, root.id)
	case entryInst.ClassName == "Script" || entryInst.ClassName == "LocalScript":
		// Scripts aren't requirable; run the body closure directly, with a require
		// bound to the script so its string requires resolve.
		fmt.Fprintf(&b, "return i%d._impl(i%d, function(p) return moduleRequire(i%d, p) end)\n",
			entryInst.id, entryInst.id, entryInst.id)
	default:
		fmt.Fprintf(&b, "return rotorRequire(i%d)\n", entryInst.id)
	}
	return b.String(), nil
}

func emitImpl(b *strings.Builder, n *Instance) {
	if _, diags := cst.Parse(n.Source); len(diags) != 0 {
		d := diags[0]
		fmt.Fprintf(b, "i%d._impl = function(script, require) error(%s) end\n",
			n.id, luauString(fmt.Sprintf("rotor pack: %s failed to compile at %d:%d: %s",
				n.Name, d.Pos.Line, d.Pos.Col, d.Message)))
		return
	}
	fmt.Fprintf(b, "i%d._impl = function(script, require)\n", n.id)
	b.WriteString(n.Source)
	if !strings.HasSuffix(n.Source, "\n") {
		b.WriteByte('\n')
	}
	b.WriteString("end\n")
}

func resolveEntry(root *Instance, path string) *Instance {
	segs := strings.Split(path, ".")
	cur := root
	i := 0
	if len(segs) > 0 && segs[0] == root.Name {
		i = 1
	}
	for ; i < len(segs); i++ {
		cur = childByName(cur, segs[i])
		if cur == nil {
			return nil
		}
	}
	return cur
}

func childByName(inst *Instance, name string) *Instance {
	for _, c := range inst.Children {
		if c.Name == name {
			return c
		}
	}
	return nil
}

func luauString(s string) string {
	var b strings.Builder
	b.WriteByte('"')
	for i := 0; i < len(s); i++ {
		switch c := s[i]; c {
		case '"':
			b.WriteString("\\\"")
		case '\\':
			b.WriteString("\\\\")
		case '\n':
			b.WriteString("\\n")
		case '\r':
			b.WriteString("\\r")
		case '\t':
			b.WriteString("\\t")
		default:
			if c < 0x20 {
				fmt.Fprintf(&b, "\\%d", c)
			} else {
				b.WriteByte(c)
			}
		}
	}
	b.WriteByte('"')
	return b.String()
}
